'use strict';

const WORDS = [
  // ===== animals（動物）=====
  { id: 'inu',        romaji: 'inu',        label: 'いぬ',       image: 'inu.png',        category: 'animals' },
  { id: 'neko',       romaji: 'neko',       label: 'ねこ',       image: 'neko.png',       category: 'animals' },
  { id: 'usagi',      romaji: 'usagi',      label: 'うさぎ',     image: 'usagi.png',      category: 'animals' },
  { id: 'kuma',       romaji: 'kuma',       label: 'くま',       image: 'kuma.png',       category: 'animals' },
  { id: 'kirin',      romaji: 'kirin',      label: 'きりん',     image: 'kirin.png',      category: 'animals' },
  { id: 'zou',        romaji: 'zou',        label: 'ぞう',       image: 'zou.png',        category: 'animals' },
  { id: 'saru',       romaji: 'saru',       label: 'さる',       image: 'saru.png',       category: 'animals' },
  { id: 'kani',       romaji: 'kani',       label: 'かに',       image: 'kani.png',       category: 'animals' },
  { id: 'tori',       romaji: 'tori',       label: 'とり',       image: 'tori.png',       category: 'animals' },
  { id: 'uma',        romaji: 'uma',        label: 'うま',       image: 'uma.png',        category: 'animals' },
  { id: 'ushi',       romaji: 'ushi',       label: 'うし',       image: 'ushi.png',       category: 'animals' },
  { id: 'buta',       romaji: 'buta',       label: 'ぶた',       image: 'buta.png',       category: 'animals' },
  { id: 'hitsuji',    romaji: 'hitsuji',    label: 'ひつじ',     image: 'hitsuji.png',    category: 'animals' },
  { id: 'niwatori',   romaji: 'niwatori',   label: 'にわとり',   image: 'niwatori.png',   category: 'animals' },
  { id: 'kingyo',     romaji: 'kingyo',     label: 'きんぎょ',   image: 'kingyo.png',     category: 'animals' },
  { id: 'kame',       romaji: 'kame',       label: 'かめ',       image: 'kame.png',       category: 'animals' },
  { id: 'tora',       romaji: 'tora',       label: 'とら',       image: 'tora.png',       category: 'animals' },
  { id: 'hebi',       romaji: 'hebi',       label: 'へび',       image: 'hebi.png',       category: 'animals' },
  { id: 'kaeru',      romaji: 'kaeru',      label: 'かえる',     image: 'kaeru.png',      category: 'animals' },
  { id: 'panda',      romaji: 'panda',      label: 'パンダ',     image: 'panda.png',      category: 'animals' },
  { id: 'pengin',     romaji: 'pengin',     label: 'ペンギン',   image: 'pengin.png',     category: 'animals' },
  { id: 'kujira',     romaji: 'kujira',     label: 'くじら',     image: 'kujira.png',     category: 'animals' },
  { id: 'iruka',      romaji: 'iruka',      label: 'いるか',     image: 'iruka.png',      category: 'animals' },
  { id: 'raion',      romaji: 'raion',      label: 'ライオン',   image: 'raion.png',      category: 'animals' },

  // ===== food（食べ物）=====
  { id: 'ringo',      romaji: 'ringo',      label: 'りんご',     image: 'ringo.png',      category: 'food' },
  { id: 'banana',     romaji: 'banana',     label: 'ばなな',     image: 'banana.png',     category: 'food' },
  { id: 'mikan',      romaji: 'mikan',      label: 'みかん',     image: 'mikan.png',      category: 'food' },
  { id: 'ichigo',     romaji: 'ichigo',     label: 'いちご',     image: 'ichigo.png',     category: 'food' },
  { id: 'suika',      romaji: 'suika',      label: 'すいか',     image: 'suika.png',      category: 'food' },
  { id: 'onigiri',    romaji: 'onigiri',    label: 'おにぎり',   image: 'onigiri.png',    category: 'food' },
  { id: 'sushi',      romaji: 'sushi',      label: 'すし',       image: 'sushi.png',      category: 'food' },
  { id: 'ramen',      romaji: 'ramen',      label: 'ラーメン',   image: 'ramen.png',      category: 'food' },
  { id: 'keki',       romaji: 'keki',       label: 'ケーキ',     image: 'keki.png',       category: 'food' },
  { id: 'purin',      romaji: 'purin',      label: 'プリン',     image: 'purin.png',      category: 'food' },
  { id: 'ume',        romaji: 'ume',        label: 'うめ',       image: 'ume.png',        category: 'food' },
  { id: 'nashi',      romaji: 'nashi',      label: 'なし',       image: 'nashi.png',      category: 'food' },
  { id: 'momo',       romaji: 'momo',       label: 'もも',       image: 'momo.png',       category: 'food' },
  { id: 'budou',      romaji: 'budou',      label: 'ぶどう',     image: 'budou.png',      category: 'food' },
  { id: 'melon',      romaji: 'melon',      label: 'メロン',     image: 'melon.png',      category: 'food' },
  { id: 'pan',        romaji: 'pan',        label: 'パン',       image: 'pan.png',        category: 'food' },
  { id: 'gohan',      romaji: 'gohan',      label: 'ごはん',     image: 'gohan.png',      category: 'food' },
  { id: 'udon',       romaji: 'udon',       label: 'うどん',     image: 'udon.png',       category: 'food' },
  { id: 'soba',       romaji: 'soba',       label: 'そば',       image: 'soba.png',       category: 'food' },
  { id: 'kare',       romaji: 'kare',       label: 'カレー',     image: 'kare.png',       category: 'food' },
  { id: 'pizza',      romaji: 'pizza',      label: 'ピザ',       image: 'pizza.png',      category: 'food' },
  { id: 'choko',      romaji: 'choko',      label: 'チョコ',     image: 'choko.png',      category: 'food' },
  { id: 'aisu',       romaji: 'aisu',       label: 'アイス',     image: 'aisu.png',       category: 'food' },
  { id: 'taiyaki',    romaji: 'taiyaki',    label: 'たいやき',   image: 'taiyaki.png',    category: 'food' },
  { id: 'dango',      romaji: 'dango',      label: 'だんご',     image: 'dango.png',      category: 'food' },
  { id: 'mochi',      romaji: 'mochi',      label: 'もち',       image: 'mochi.png',      category: 'food' },
  { id: 'donatsu',    romaji: 'donatsu',    label: 'ドーナツ',   image: 'donatsu.png',    category: 'food' },
  { id: 'hambaga',    romaji: 'hambaga',    label: 'ハンバーガー',image: 'hambaga.png',   category: 'food' },
  { id: 'poteto',     romaji: 'poteto',     label: 'ポテト',     image: 'poteto.png',     category: 'food' },
  { id: 'takoyaki',   romaji: 'takoyaki',   label: 'たこやき',   image: 'takoyaki.png',   category: 'food' },

  // ===== vehicles（乗り物）=====
  { id: 'kuruma',     romaji: 'kuruma',     label: 'くるま',     image: 'kuruma.png',     category: 'vehicles' },
  { id: 'basu',       romaji: 'basu',       label: 'バス',       image: 'basu.png',       category: 'vehicles' },
  { id: 'densha',     romaji: 'densha',     label: 'でんしゃ',   image: 'densha.png',     category: 'vehicles' },
  { id: 'jitensha',   romaji: 'jitensha',   label: 'じてんしゃ', image: 'jitensha.png',   category: 'vehicles' },
  { id: 'hikoki',     romaji: 'hikoki',     label: 'ひこうき',   image: 'hikoki.png',     category: 'vehicles' },
  { id: 'fune',       romaji: 'fune',       label: 'ふね',       image: 'fune.png',       category: 'vehicles' },
  { id: 'shinkansen', romaji: 'shinkansen', label: 'しんかんせん',image: 'shinkansen.png', category: 'vehicles' },
  { id: 'baiku',      romaji: 'baiku',      label: 'バイク',     image: 'baiku.png',      category: 'vehicles' },
  { id: 'torakku',    romaji: 'torakku',    label: 'トラック',   image: 'torakku.png',    category: 'vehicles' },
  { id: 'takushi',    romaji: 'takushi',    label: 'タクシー',   image: 'takushi.png',    category: 'vehicles' },
  { id: 'shobosha',   romaji: 'shobosha',   label: 'しょうぼうしゃ',image:'shobosha.png', category: 'vehicles' },
  { id: 'roketto',    romaji: 'roketto',    label: 'ロケット',   image: 'roketto.png',    category: 'vehicles' },
  { id: 'herikoputa', romaji: 'herikoputa', label: 'ヘリコプター',image: 'herikoputa.png', category: 'vehicles' },
  { id: 'sukuta',     romaji: 'sukuta',     label: 'スクーター', image: 'sukuta.png',     category: 'vehicles' },
  { id: 'sanrinsha',  romaji: 'sanrinsha',  label: 'さんりんしゃ',image:'sanrinsha.png',  category: 'vehicles' },
  { id: 'monoreru',   romaji: 'monoreru',   label: 'モノレール', image: 'monoreru.png',   category: 'vehicles' },

  // ===== things（身近なもの）=====
  { id: 'hon',        romaji: 'hon',        label: 'ほん',       image: 'hon.png',        category: 'things' },
  { id: 'boushi',     romaji: 'boushi',     label: 'ぼうし',     image: 'boushi.png',     category: 'things' },
  { id: 'kutsu',      romaji: 'kutsu',      label: 'くつ',       image: 'kutsu.png',      category: 'things' },
  { id: 'kaban',      romaji: 'kaban',      label: 'かばん',     image: 'kaban.png',      category: 'things' },
  { id: 'kasa',       romaji: 'kasa',       label: 'かさ',       image: 'kasa.png',       category: 'things' },
  { id: 'tokei',      romaji: 'tokei',      label: 'とけい',     image: 'tokei.png',      category: 'things' },
  { id: 'terebi',     romaji: 'terebi',     label: 'テレビ',     image: 'terebi.png',     category: 'things' },
  { id: 'piano',      romaji: 'piano',      label: 'ピアノ',     image: 'piano.png',      category: 'things' },

  // ===== body（からだ）=====
  { id: 'me',         romaji: 'me',         label: 'め',         image: 'me.png',         category: 'body' },
  { id: 'kuchi',      romaji: 'kuchi',      label: 'くち',       image: 'kuchi.png',      category: 'body' },
  { id: 'mimi',       romaji: 'mimi',       label: 'みみ',       image: 'mimi.png',       category: 'body' },
  { id: 'te',         romaji: 'te',         label: 'て',         image: 'te.png',         category: 'body' },
  { id: 'ashi',       romaji: 'ashi',       label: 'あし',       image: 'ashi.png',       category: 'body' },
  { id: 'atama',      romaji: 'atama',      label: 'あたま',     image: 'atama.png',      category: 'body' },
  { id: 'kami',       romaji: 'kami',       label: 'かみ（かみのけ）',image: 'kami.png',  category: 'body' },
  { id: 'kubi',       romaji: 'kubi',       label: 'くび',       image: 'kubi.png',       category: 'body' },
  { id: 'onaka',      romaji: 'onaka',      label: 'おなか',     image: 'onaka.png',      category: 'body' },
  { id: 'yubi',       romaji: 'yubi',       label: 'ゆび',       image: 'yubi.png',       category: 'body' },
  { id: 'ha',         romaji: 'ha',         label: 'は（歯）',   image: 'ha.png',         category: 'body' },
  { id: 'kata',       romaji: 'kata',       label: 'かた',       image: 'kata.png',       category: 'body' },
  { id: 'hiza',       romaji: 'hiza',       label: 'ひざ',       image: 'hiza.png',       category: 'body' },
  { id: 'senaka',     romaji: 'senaka',     label: 'せなか',     image: 'senaka.png',     category: 'body' },
  { id: 'hitai',      romaji: 'hitai',      label: 'ひたい',     image: 'hitai.png',      category: 'body' },

  // ===== nature（しぜん）=====
  { id: 'hana',       romaji: 'hana',       label: 'はな（花）', image: 'hana.png',       category: 'nature' },
  { id: 'ki',         romaji: 'ki',         label: 'き（木）',   image: 'ki.png',         category: 'nature' },
  { id: 'kusa',       romaji: 'kusa',       label: 'くさ',       image: 'kusa.png',       category: 'nature' },
  { id: 'yama',       romaji: 'yama',       label: 'やま',       image: 'yama.png',       category: 'nature' },
  { id: 'kawa',       romaji: 'kawa',       label: 'かわ',       image: 'kawa.png',       category: 'nature' },
  { id: 'umi',        romaji: 'umi',        label: 'うみ',       image: 'umi.png',        category: 'nature' },
  { id: 'sora',       romaji: 'sora',       label: 'そら',       image: 'sora.png',       category: 'nature' },
  { id: 'hoshi',      romaji: 'hoshi',      label: 'ほし',       image: 'hoshi.png',      category: 'nature' },
  { id: 'tsuki',      romaji: 'tsuki',      label: 'つき',       image: 'tsuki.png',      category: 'nature' },
  { id: 'taiyou',     romaji: 'taiyou',     label: 'たいよう',   image: 'taiyou.png',     category: 'nature' },
  { id: 'kumo',       romaji: 'kumo',       label: 'くも（雲）', image: 'kumo.png',       category: 'nature' },
  { id: 'yuki',       romaji: 'yuki',       label: 'ゆき',       image: 'yuki.png',       category: 'nature' },
  { id: 'niji',       romaji: 'niji',       label: 'にじ',       image: 'niji.png',       category: 'nature' },
  { id: 'kaze',       romaji: 'kaze',       label: 'かぜ',       image: 'kaze.png',       category: 'nature' },
  { id: 'koori',      romaji: 'koori',      label: 'こおり',     image: 'koori.png',      category: 'nature' },

  // ===== colors（いろ）=====
  { id: 'aka',        romaji: 'aka',        label: 'あか',       image: 'aka.png',        category: 'colors' },
  { id: 'ao',         romaji: 'ao',         label: 'あお',       image: 'ao.png',         category: 'colors' },
  { id: 'kiiro',      romaji: 'kiiro',      label: 'きいろ',     image: 'kiiro.png',      category: 'colors' },
  { id: 'midori',     romaji: 'midori',     label: 'みどり',     image: 'midori.png',     category: 'colors' },
  { id: 'shiro',      romaji: 'shiro',      label: 'しろ',       image: 'shiro.png',      category: 'colors' },
  { id: 'kuro',       romaji: 'kuro',       label: 'くろ',       image: 'kuro.png',       category: 'colors' },
  { id: 'orenji',     romaji: 'orenji',     label: 'オレンジ',   image: 'orenji.png',     category: 'colors' },
  { id: 'murasaki',   romaji: 'murasaki',   label: 'むらさき',   image: 'murasaki.png',   category: 'colors' },
  { id: 'pinku',      romaji: 'pinku',      label: 'ピンク',     image: 'pinku.png',      category: 'colors' },
  { id: 'chairo',     romaji: 'chairo',     label: 'ちゃいろ',   image: 'chairo.png',     category: 'colors' },

  // ===== school（がっこう）=====
  { id: 'enpitsu',    romaji: 'enpitsu',    label: 'えんぴつ',   image: 'enpitsu.png',    category: 'school' },
  { id: 'keshigomu',  romaji: 'keshigomu',  label: 'けしごむ',   image: 'keshigomu.png',  category: 'school' },
  { id: 'nooto',      romaji: 'nooto',      label: 'ノート',     image: 'nooto.png',      category: 'school' },
  { id: 'hasami',     romaji: 'hasami',     label: 'はさみ',     image: 'hasami.png',     category: 'school' },
  { id: 'monosashi',  romaji: 'monosashi',  label: 'ものさし',   image: 'monosashi.png',  category: 'school' },
  { id: 'randoseru',  romaji: 'randoseru',  label: 'ランドセル', image: 'randoseru.png',  category: 'school' },
  { id: 'kokuban',    romaji: 'kokuban',    label: 'こくばん',   image: 'kokuban.png',    category: 'school' },
  { id: 'tsukue',     romaji: 'tsukue',     label: 'つくえ',     image: 'tsukue.png',     category: 'school' },
  { id: 'isu',        romaji: 'isu',        label: 'いす',       image: 'isu.png',        category: 'school' },
  { id: 'nori',       romaji: 'nori',       label: 'のり（のり）',image: 'nori.png',       category: 'school' },

  // ===== play（あそび）=====
  { id: 'booru',      romaji: 'booru',      label: 'ボール',     image: 'booru.png',      category: 'play' },
  { id: 'ningyo',     romaji: 'ningyo',     label: 'にんぎょう', image: 'ningyo.png',     category: 'play' },
  { id: 'koma',       romaji: 'koma',       label: 'こま',       image: 'koma.png',       category: 'play' },
  { id: 'buranko',    romaji: 'buranko',    label: 'ブランコ',   image: 'buranko.png',    category: 'play' },
  { id: 'suberidai',  romaji: 'suberidai',  label: 'すべりだい', image: 'suberidai.png',  category: 'play' },
  { id: 'yakyu',      romaji: 'yakyu',      label: 'やきゅう',   image: 'yakyu.png',      category: 'play' },
  { id: 'sakka',      romaji: 'sakka',      label: 'サッカー',   image: 'sakka.png',      category: 'play' },
];
